#Database
#POSTGRES_USER:
#POSTGRES_PASSWORD:
#POSTGRES_HOST:
#POSTGRES_PORT: 5432
#POSTGRES_DB:


#Server
#APPLICATION_PORT: 8085
#ACTIVE_PROFILE: prod

#mail
#EMAIL_HOST: smtp.gmail.com
#EMAIL_PORT: 587
#EMAIL_ID:
#EMAIL_PASSWORD:
#EMAIL_VERIFY_HOST: http://localhost:8085
