server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
            - Method=POST,GET,PUT,DELETE,OPTIONS
          filters:
            - RewritePath=/api/users/(?<segment>.*), /api/v1/user/${segment}
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/user-service

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**
          filters:
            - RewritePath=/api/tasks/(?<segment>.*), /api/v1/task/${segment}
            - name: CircuitBreaker
              args:
                name: taskService
                fallbackUri: forward:/fallback/task-service

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
#       defaultZone: http://localhost:8761/eureka  # TODO для запуска в Idea
management:
  endpoints:
    web:
      exposure:
        include: '*'

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      userService:
        baseConfig: default
      taskService:
        baseConfig: default


logging:
  level:
    org.springframework.cloud.gateway: DEBUG