<script setup>
import { computed, onMounted, ref } from 'vue'

import EmptyState from '../components/EmptyState.vue'
import ErrorMessage from '../components/ErrorMessage.vue'
import LoadingIndicator from '../components/LoadingIndicator.vue'
import NotificationList from '../components/NotificationList.vue'
import { getUserFriendlyError } from '../services/apiClient'
import { getNotifications } from '../services/notificationService'

const PAGE_SIZE = 20

const notifications = ref([])
const page = ref({ number: 0, size: PAGE_SIZE, totalElements: 0, totalPages: 0 })
const isLoading = ref(false)
const error = ref(null)
let requestId = 0

const currentPage = computed(() => page.value.number + 1)
const displayedTotalPages = computed(() => Math.max(page.value.totalPages, 1))
const hasPreviousPage = computed(() => page.value.number > 0)
const hasNextPage = computed(() => page.value.number + 1 < page.value.totalPages)

function notificationListError(requestError) {
  return getUserFriendlyError(requestError, {
    fallback: 'Unable to load notifications. Please try again.',
    networkMessage: 'Unable to reach the notification service. Check that the backend is running.',
    statusMessages: {
      403: 'You do not have permission to view notifications.',
      500: 'The notification service is unavailable. Please try again later.',
    },
  })
}

async function loadNotifications(targetPage = page.value.number) {
  const activeRequestId = ++requestId
  isLoading.value = true
  error.value = null

  try {
    const response = await getNotifications({
      page: targetPage,
      size: PAGE_SIZE,
      sort: 'createdAt,desc',
    })

    if (activeRequestId !== requestId) {
      return
    }

    notifications.value = Array.isArray(response?.data?.items) ? response.data.items : []
    page.value = {
      number: response?.data?.page?.number ?? targetPage,
      size: response?.data?.page?.size ?? PAGE_SIZE,
      totalElements: response?.data?.page?.totalElements ?? notifications.value.length,
      totalPages: response?.data?.page?.totalPages ?? 0,
    }
  } catch (requestError) {
    if (activeRequestId === requestId) {
      notifications.value = []
      error.value = notificationListError(requestError)
    }
  } finally {
    if (activeRequestId === requestId) {
      isLoading.value = false
    }
  }
}

function previousPage() {
  if (hasPreviousPage.value) {
    loadNotifications(page.value.number - 1)
  }
}

function nextPage() {
  if (hasNextPage.value) {
    loadNotifications(page.value.number + 1)
  }
}

onMounted(() => loadNotifications(0))
</script>

<template>
  <section>
    <h1>Notifications</h1>

    <LoadingIndicator v-if="isLoading" message="Loading notifications..." />

    <ErrorMessage
      v-else-if="error"
      :message="error"
      retry-label="Retry"
      @retry="loadNotifications()"
    />

    <template v-else>
      <EmptyState
        v-if="notifications.length === 0"
        title="No notifications"
        message="New notifications generated by the platform will appear here."
      />
      <NotificationList v-else :notifications="notifications" />

      <div class="pagination" aria-label="Notification list pagination">
        <button type="button" :disabled="!hasPreviousPage" @click="previousPage">
          Previous
        </button>
        <span>
          Page {{ currentPage }} of {{ displayedTotalPages }}
          ({{ page.totalElements }} notifications)
        </span>
        <button type="button" :disabled="!hasNextPage" @click="nextPage">
          Next
        </button>
      </div>
    </template>
  </section>
</template>
