server:
  port: 8888

spring:
  profiles:
    active: native # active profile for config server
  application:
    name: config-server

  cloud:
    config:
      server:
         native:
           search-locations: file:../../config/ # local file system - config in root
#        git:
#          uri: https://github.com/davidav/tsp-config.git # Git configuration server
#          clone-on-start: true
#          default-label: main


management:
  endpoints:
    web:
      exposure:
        include: '*'


